### PR TITLE
feature/integrate-with-codeclimate

### PR DESCRIPTION
**Pull request by KennethanCeyer**
## 🚀 Features

- Add codeclimate integration (coverage, code quality)
- Add workflow for testing, coveraging
- Update README.md

## Coverage integration

You can check by entering into below link

https://codeclimate.com/repos/60fd83052952e501a1000f8e/settings/test_reporter

image

The integration seems working

### CODE REVIEW

**Comment by zi-gae** [comment]
https://codeclimate.com/repos/60fd83052952e501a1000f8e/settings/test_reporter page authority impossible to check

**Comment by KennethanCeyer** [comment]
@devGW

Oh.. I'm not familiar with the codeclimate permission...
Could you confirm one thing for me? 🙏 

Codeclimate Open source zap repo is now connected.
All current maintainers have zap repo privileges set to **Admin**.

In other words,
after connecting to [codeclimate](https://codeclimate.com/oss/dashboard)
you can see the zap repo if you sync in the Open source section. Can you give it a try?

**Comment by zi-gae** [comment]
> @devGW
> 
> Oh.. I'm not familiar with the codeclimate permission...
> Could you confirm one thing for me? 🙏
> 
> Codeclimate Open source zap repo is now connected.
> All current maintainers have zap repo privileges set to **Admin**.
> 
> In other words,
> after connecting to [codeclimate](https://codeclimate.com/oss/dashboard)
> you can see the zap repo if you sync in the Open source section. Can you give it a try?

I will try, thanks :)

**Comment by KennethanCeyer** [comment]
@zi-gae 

During initial setup (at least while blogging)
I'm going to turn off the **Review Required** option for the protected branch. (only for develop branch, master is still under the protected branch)
However, you can leave a review at any time! (And I'll reflect the review as soon as it is left)

This aims to get the cycle up to the initial setup of blog development relatively fast.

**Comment by zi-gae** [comment]
> @zi-gae
> 
> During initial setup (at least while blogging) I'm going to turn off the **Review Required** option for the protected branch. (only for develop branch, master is still under the protected branch) However, you can leave a review at any time! (And I'll reflect the review as soon as it is left)
> 
> This aims to get the cycle up to the initial setup of blog development relatively fast.

I agree with this discussion 🙆🏼

**Pull request merged**
